# Versão final e corrigida do docker-compose.yml
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_tsdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    # --- Configuração automática do InfluxDB ---
    # Na primeira inicialização, ele criará tudo que precisamos.
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=SEU USUARIO
      - DOCKER_INFLUXDB_INIT_PASSWORD=SUA SENHA
      - DOCKER_INFLUXDB_INIT_ORG=minha_org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_bucket
      # Este é o mesmo token do seu script subscriber.py
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=COLOQUE SEU TOKER AQUI
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: unless-stopped

  simulador:
    build: ./simulador_py
    container_name: python_simulator
    restart: on-failure
    dns:
      - 8.8.8.8
      - 1.1.1.1

  subscriber:
    build: ./subscriber_py
    container_name: python_subscriber
    depends_on:
      - influxdb
    restart: on-failure
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  influxdb_data:
